---
title: "ImmuneSignatures 2 Project - Create Final ExpressionSets"
author: "Evan Henrich"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
```

```{r load-dependencies}
library(ImmuneSignatures2) # vaccine map loaded as `vaccines`
library(Biobase)
library(dplyr)
library(data.table)
library(titer) # devtools::install_github("stefanavey/titer")
library(massiR)
library(limma)
```

```{r output-variables}
outputDir <- "/home/evanhenrich/Documents/FHCRC/IS2_OUTPUT/"
filenamePrefix <- "2020_06_15_"

postVaxDayRanges <- list(
  hai = c(20,46),
  neut_ab_titer = c(28,90),
  elisa = c(21,30)
)

discretizationValues <- list(
    "RBA" = c(0.3, 0.4, 0.5),
    "MFC" = c(0.3, 0.4)
)

young <- c(18,50)
  old <- c(60,91)
ageGroups <- list(
  young = young,
  old = old,
  youngAndOld = c(young, old),
  all = c(min(young), max(old))
)

targetDistributionVendor <- "Affymetrix"
targetDistributionExcludedStudies <- "SDY1293"
```

```{r load-base-data}
immdata_all <- readRDS(paste0(outputDir, "/", filenamePrefix, "immdata_all.rds"))
noNormEset <- readRDS(paste0(outputDir, "/", filenamePrefix, "noNormEset.rds"))
```

```{r create-final-esets-function}
createFinalEset <- function(noNormEset, immdata_all, ages, ageGroupName,
                            crossStudyNormalize, targetDistributionVendor,
                            targetDistributionExcludedStudies,
                            addResponseCall, postVaxDayRanges, discretizationValues,
                            outputDir, filenamePrefix){
  
  eset <- filterEsetByAge(noNormEset, ages)
  eset <- removeAllNArows(eset)
  
  if(crossStudyNormalize){
    eset <- crossStudyNormalize(eset, targetDistributionVendor, targetDistributionExcludedStudies)
    eset <- batchCorrectBaselineData(eset)
    eset <- removeAllNArows(eset)
    normSuffix <- "norm"
  }else{
    normSuffix <- "noNorm"
  }
  
  if(addResponseCall){
    filteredImmdata <- filterImmdataByAge(immdata_all, ages)
    immdataWithResponses <- lapply(names(filteredImmdata), function(assay){
      dataWithResponses <- generateResponseCall(
        assay = assay,
        data = filteredImmdata[[assay]],
        postVaxDayRange = postVaxDayRanges[[assay]],
        discretizationValues = discretizationValues
      )
    })
    selectedImmdata <- selectResponsesToUse(immdataWithResponses)
    eset <- addResponseData(eset, selectedImmdata)
    responseSuffix <- "withResponse"
  }else{
    responseSuffix <- "noResponse"
  }
  
  res <- testFinalEset(eset, 
                       expectResponse = addResponseCall, 
                       expectNormalization = crossStudyNormalize, 
                       ages)
  
  if(!all(unlist(res))){
    esetName <- paste(normSuffix, responseSuffix)
    msg <- paste0("eset failed: ", esetName, "\n", 
                  "For Ages: ", paste(ages, collapse = " "), "\n")
    stop(msg)
  }
  
  fullSuffix <- paste0(ageGroupName, "_", normSuffix, "_", responseSuffix, "_eset.rds")
  filename <- paste0(filenamePrefix, fullSuffix)
  outputFile <- paste0(outputDir, filename)
  
  saveRDS(eset, outputFile)
}
```

```{r create-variants-of-final-eset}
for(ageGroupName in names(ageGroups)){
  for(crossStudyNormalize in c(TRUE, FALSE)){
    for(addResponseCall in c(TRUE, FALSE)){
      createFinalEset(noNormEset = noNormEset,
                      immdata_all = immdata_all,
                      ages = ageGroups[[ageGroupName]],
                      ageGroupName = ageGroupName,
                      crossStudyNormalize = crossStudyNormalize,
                      addResponseCall = addResponseCall,
                      targetDistributionVendor = targetDistributionVendor,
                      targetDistributionExcludedStudies = targetDistributionExcludedStudies,
                      postVaxDayRanges = postVaxDayRanges,
                      discretizationValues = discretizationValues,
                      outputDir = outputDir,
                      filenamePrefix = filenamePrefix)
    }
  }
}
```
