---
title: "Data Summary"
output: html_document
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      message = FALSE,
                      warning = FALSE)
```

```{r libraries}
suppressPackageStartupMessages({
  library(ImmuneSignatures2)
  library(Biobase)
  library(data.table)
  library(Rlabkey)
})
```

```{r, global-variables}
dataCacheDir <- "data_cache"
datePrefix <- "2020_12_07_"
datePrefix <- "2020_10_27"
```

```{r load, echo = FALSE}

immdata_all <- readRDS(here::here(dataCacheDir, "2020_10_27_immdata_all.rds"))
IS2_esets <- readRDS(here::here(dataCacheDir, "2020_10_27_IS2_esets.rds"))
```

## Subject summaries by dataset

For all versions of data

```{r subjects}
summary <- data.table(cohorts = c(),
                      subjects = c(),
                      studies = c(),
                      samples = c(),
                      vaccines = c(),
                      vaccine_types = c())
esets <- list.files(here::here(dataCacheDir), pattern = "_eset.rds")
datasetSummaries <- lapply(esets, function(filename) {
  dataset <- readRDS(here::here(dataCacheDir, filename))
  
  pdata_all <- phenoData(dataset)
  d <- pdata_all@data
  cohort_count <- length(unique(d$arm_accession))
  # subject_count <- length(unique(gsub("\\.\\d+", "", d$participant_id)))
  subject_count <- length(unique(d$participant_id))
  sample_count <- length(unique(d$biosample_accession))
  summary_datset <- data.table(
    dataset = filename,
    cohorts = cohort_count, 
    subjects = subject_count, 
    samples = sample_count)
})
knitr::kable(rbindlist(datasetSummaries))
```

## Study summaries by dataset

Only looking at full datasets (not divided by age)

```{r studies}
esets_all <- esets <- list.files(here::here(dataCacheDir), pattern = "_all_")
dimstudy <- labkey.selectRows("https://test.immunespace.org/", 
                              folderPath = "HIPC/IS2", 
                              schemaName = "immport", 
                              queryName = "dimstudy", 
                              colSelect = c("study", "program"),
                              colNameOpt = "rname")
datasetSummaries <- lapply(esets_all, function(filename) {
  dataset <- readRDS(here::here("data_cache", filename))
  
  pdata_all <- phenoData(dataset)
  d <- data.table(pdata_all@data)
  d <- merge(d, dimstudy, by.x = "study_accession", by.y = "study")
  cohort_count <- length(unique(d$arm_accession))
  study_count <- length(unique(d$study_accession))
  vaccine_count <- length(unique(d$vaccine))
  vaccine_type_count <- length(unique(d$vaccine_type))
  pathogen_count <- length(unique(d$pathogen))
  
  studyProgram <- unique(d[, .(study_accession, program)])
  studyProgram[, hipc := grepl("HIPC", program)]
  hipc_studies <- sum(studyProgram$hipc)
  not_hipc_studies <- sum(!studyProgram$hipc)
  summary_datset <- data.table(
    dataset = filename,
    studies = study_count, 
    vaccines = vaccine_count, 
    vaccine_types = vaccine_type_count,
    pathogens = pathogen_count,
    hipc_studies = hipc_studies,
    not_hipc_studies = not_hipc_studies)
})
knitr::kable(rbindlist(datasetSummaries))
```
